name: Java CI/CD with Maven and Jenkins

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    - name: Run Tests
      run: mvn test
    
    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: insurance-app-war
        path: target/*.war
    
    - name: Copy WAR to Server via SSH Key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "target/insurance-app.war"
        target: "/tmp/target/"
        strip_components: 1
    
    - name: Trigger Jenkins Deployment
      run: |
        echo "Triggering Jenkins job: TomcatDeployment"
        curl -X POST \
          http://${{ secrets.HOST }}:8080/job/TomcatDeployment/build \
          --user admin:${{ secrets.JENKINS_TOKEN }}
        
        echo "Waiting for deployment..."
        sleep 30
        
        echo "=========================================="
        echo "✅ Pipeline completed!"
        echo "Application: http://${{ secrets.HOST }}:8080/insurance-app"
        echo "=========================================="
