name: Java CI/CD with Maven and Jenkins

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Step 3: Build with Maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    # Step 4: Run tests
    - name: Run Tests
      run: mvn test
    
    # Step 5: Upload WAR artifact
    - name: Upload WAR file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: insurance-app-war
        path: target/*.war
    
    # Step 6: Copy WAR to server via SCP
    - name: Copy WAR to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/insurance-app.war"
        target: "/tmp/target/"
        strip_components: 1
    
    # Step 7: Trigger Jenkins deployment job
    - name: Trigger Jenkins Deployment
      run: |
        echo "Triggering Jenkins job: TomcatDeployment"
        curl -X POST \
          http://${{ secrets.HOST }}:8082/job/TomcatDeployment/build \
          --user admin:${{ secrets.JENKINS_TOKEN }}
        
        echo "Waiting for deployment to complete..."
        sleep 30
        
        echo "=========================================="
        echo "✅ Pipeline completed successfully!"
        echo "Application URL: http://${{ secrets.HOST }}:8080/insurance-app"
        echo "=========================================="
